#!/bin/bash

# script to run FSL "randomise" on only those brain areas that are actually part of the indendent components that are being analyzed

# modules
module load fsl

# variables
OUTPUT=scratch/dualreg # SET THIS; output directory (e.g. scratch/randomise)
LOGDIR=$OUTPUT/scripts+logs # SET THIS; log directory (e.g. scratch/randomise/scripts+dir)

ICA_MAPS=yeo17.nii.gz # SET THIS; the IC file (e.g. Yeo17 or MELODIC)
pICMASK=$OUTPUT/pICMASK
nICMASK=$OUTPUT/nICMASK
fslmaths $ICA_MAPS -thr 0.2 -bin ${pICMASK} 
fslmaths $ICA_MAPS -mul -1 -thr 0.2 -bin ${nICMASK}

DESIGN=yourdesign.mat # SET THIS; design matrix
CONTRAST=yourcontrast.con # SET THIS; contrast matrix
NPERM=1000 # SET THIS; number of permutations


j=0
Nics=`$FSLDIR/bin/fslnvols ${pICMASK}`
echo "Using $Nics masks (two-sided)"

while [ $j -lt $Nics ] ; do
  
    jj=`$FSLDIR/bin/zeropad $j 4`
    
    # make masks based on component $j
    for pref in pICMASK nICMASK; do
	
	ICMASKj=${pref}${j}
	fslroi ${OUTPUT}/${pref} $OUTPUT/$ICMASKj $j 1
	
	RAND=""

	RAND="$FSLDIR/bin/randomise -i $OUTPUT/dr_stage2_ic$jj -o $OUTPUT/dr_stage3_ic${jj}${pref%%IC*} -m $OUTPUT/$ICMASKj -d $DESIGN -m $CONTRAST -n $NPERM -x -T"
	
	echo "$FSLDIR/bin/fslmerge -t $OUTPUT/dr_stage2_ic$jj \`\$FSLDIR/bin/imglob $OUTPUT/dr_stage2_subject*_ic${jj}.*\` ; \
        $FSLDIR/bin/imrm \`\$FSLDIR/bin/imglob $OUTPUT/dr_stage2_subject*_ic${jj}.*\` ; $RAND" >> ${LOGDIR}/drD_copy
	
    done
    
    j=`echo "$j 1 + p" | dc -`
    
done
